### ISSUE TITLE
感觉是不是给1-2个运行实例在README中写下来会好点

### ISSUE THREAD

**Issue by fengshaw1** [ybdai7/Backdoor-indicator-defense#2]
有点不知道怎么配置运行了，感觉README写的有点模糊
![image](https://github.com/ybdai7/Backdoor-indicator-defense/assets/57137032/592bbcb8-c27d-4297-b15a-6e296ccb1999)
这块是让新建一个yaml文件然后填上对应的内容就能运行吗请问，跑起来报错频繁，能否给几个示例，谢谢！

**Comment by ybdai7** [comment]
Hi,

Thanks for your question and i am sorry for the misunderstanding that may caused. Here, it means to modify `poisoned_start_round`, `global_watermarking_start_round` to 10000 in the given `utils/yamls/indicator/params_vanilla_Indicator.yaml`. Then you could save some checkpoints of the global model, and change the `resumed_model` to the corresponding path of the saved checkpoint. Then you could set `poisoned_start_round`, `global_watermarking_start_round` to whatever you want.

And of course you could ignore this part, and just start the FL training from scratch with any `poisoned_start_round`, `global_watermarking_start_round` you like.

Please feel free to post any error message that occurs. I will try to resolve it.

Thanks.

**Comment by fengshaw1** [comment]
ok, thanks a lot. Maybe this README can be changed, i see it may have some problem.
