### ISSUE TITLE
可否提供一下模型

### ISSUE THREAD

**Issue by liang5211314** [ybdai7/Backdoor-indicator-defense#3]
![289c25613ec5a9e63dcd89e11526d9f](https://github.com/ybdai7/Backdoor-indicator-defense/assets/44901475/892ed110-d4a8-4309-a8e3-87f4022f4e59)
![image](https://github.com/ybdai7/Backdoor-indicator-defense/assets/44901475/351820d0-b54f-4c40-86f5-e24ebd5f95d1)

**Comment by ybdai7** [comment]
Hi,

For the edge-case datasets, you can acquire them following the instructions of https://github.com/ksreenivasan/OOD_Federated_Learning, which is the official repo of the Yes-you-can-really-backdoor-FL paper.

Thanks
