### ISSUE TITLE
Global DataLoader issue

### ISSUE THREAD

**Issue by gsiros** [ybdai7/Backdoor-indicator-defense#4]
I am running: 
```
python main.py --GPU_id "0" --params utils/yamls/nodefense/params_vanilla_Nodefense.yaml
```
but I am getting the following error:
```
current path:./saved_models/Sep.03_10.36.49
start training from the 1st round
Traceback (most recent call last):
  File "main.py", line 117, in <module>
    test_dataloader=dataloader.test_data,
TypeError: broadcast_upload() missing 1 required positional argument: 'global_dataloader'
```

**Comment by ybdai7** [comment]
Hi,

Thanks for the question. The repo is updated, and you can pull from the newest version to fix this problem.

The case is that i forget to remove redundant attributes for all server files. Please feel free to contact if there are further problems.

Yanbo

**Comment by gsiros** [comment]
Hi Yanbo, 

Thanks for fixing the repo. It all seems to work now.
