### ISSUE TITLE
Why did the experiment seem to stop after 1800 rounds?

### ISSUE THREAD

**Issue by fengshaw1** [ybdai7/Backdoor-indicator-defense#5]
Before 1800 rounds, the epoch number will continue to be displayed, but after 1800 rounds, this number is no longer displayed. Why is this?
![image](https://github.com/user-attachments/assets/6ad5b051-38e1-4f50-b99b-9cfea3dae673)

**Comment by ybdai7** [comment]
Hi,

I dont really understand your question, and the log file does not seem to match with the style of this repo. But if you mean how to modify when the training ends, you may change the "end_round" parameters in yaml file, which is set to 1900 by default.

**Comment by fengshaw1** [comment]
sorry！look your this repo. 
https://github.com/ybdai7/Chameleon-durable-backdoor/issues
